-- Services only - UTF-8 encoded
INSERT OR IGNORE INTO services (id, slug, title, title_en, description, description_en, content, content_en, specs, price, currency, tags, service_type, category_id, image_url, gallery, is_active) VALUES
(50, 'gida-analiz-hizmeti', 'Gida Analiz Hizmeti', 'Food Analysis Service', 'Komple gida analiz ve raporlama hizmeti.', 'Complete food analysis and reporting service.', '<h2>Hizmet Kapsami</h2><ul><li>Mikrobiyolojik analiz</li><li>Kimyasal analiz</li><li>Fiziksel analiz</li><li>Raporlama</li></ul>', '<h2>Service Scope</h2><ul><li>Microbiological analysis</li><li>Chemical analysis</li><li>Physical analysis</li><li>Reporting</li></ul>', '{"turnaround_time": "5-7 is gunu", "sample_types": ["Gida", "Su", "Cevre"], "methods": ["ISO 17025"]}', 2500.00, 'TRY', '["gida", "analiz", "rapor"]', 'analysis', 50, '/api/media/serve/forlabs/services/2026/03/gida-analiz-nop678.jpg', '["/api/media/serve/forlabs/services/2026/03/analiz-lab-1-qrs234.jpg", "/api/media/serve/forlabs/services/2026/03/analiz-lab-2-tuv567.jpg"]', 1),

(51, 'ph-metre-kalibrasyonu', 'pH Metre Kalibrasyonu', 'pH Meter Calibration', 'Profesyonel pH metre kalibrasyon ve dogrulama.', 'Professional pH meter calibration and verification.', '<h2>Kalibrasyon Sureci</h2><ul><li>3 nokta kalibrasyon</li><li>Sertifika</li><li>Dogruluk testi</li></ul>', '<h2>Calibration Process</h2><ul><li>3-point calibration</li><li>Certificate</li><li>Accuracy test</li></ul>', '{"calibration_points": ["pH 4.01", "pH 7.00", "pH 10.01"], "certificate": "ISO 17025", "validity": "1 yil"}', 850.00, 'TRY', '["kalibrasyon", "ph", "sertifika"]', 'calibration', 51, '/api/media/serve/forlabs/services/2026/03/ph-kalibrasyon-wxy890.jpg', '["/api/media/serve/forlabs/services/2026/03/kalibrasyon-1-zab123.jpg"]', 1),

(52, 'laboratuvar-egitimi', 'Laboratuvar Egitimi', 'Laboratory Training', 'Temel laboratuvar teknikleri egitimi.', 'Basic laboratory techniques training.', '<h2>Egitim Icerigi</h2><ul><li>Guvenlik</li><li>Pipetleme</li><li>Analiz teknikleri</li></ul>', '<h2>Training Content</h2><ul><li>Safety</li><li>Pipetting</li><li>Analysis techniques</li></ul>', '{"duration": "2 gun", "participants": "Max 10 kisi", "certificate": "Katilim Sertifikasi"}', 3500.00, 'TRY', '["egitim", "laboratuvar", "teknik"]', 'training', 52, '/api/media/serve/forlabs/services/2026/03/lab-egitim-cde456.jpg', '["/api/media/serve/forlabs/services/2026/03/egitim-1-fgh789.jpg"]', 1),

(53, 'laboratuvar-kurulum-danismanligi', 'Laboratuvar Kurulum Danismanligi', 'Laboratory Setup Consulting', 'Laboratuvar kurulum ve tasarim danismanligi.', 'Laboratory setup and design consulting.', '<h2>Danismanlik Hizmetleri</h2><ul><li>Tasarim</li><li>Ekipman secimi</li><li>Kurulum</li><li>Validasyon</li></ul>', '<h2>Consulting Services</h2><ul><li>Design</li><li>Equipment selection</li><li>Installation</li><li>Validation</li></ul>', '{"scope": "Turnkey", "timeline": "3-6 ay", "deliverables": ["Proje", "Ekipman", "Egitim"]}', 15000.00, 'TRY', '["danismanlik", "kurulum", "tasarim"]', 'consulting', 53, '/api/media/serve/forlabs/services/2026/03/danismanlik-rstu345.jpg', '["/api/media/serve/forlabs/services/2026/03/danismanlik-1-vwx678.jpg"]', 1);
