// Re-export all API functions and types from @forlabs/core
export {
  getProducts,
  getProduct,
  getArticles,
  getArticle,
  getServices,
  getService,
  getCategories,
  getPages,
  getNavigations,
  getProjects,
  getProject,
  submitInquiry,
  initializeCheckout,
  getWizardSteps,
  postMatch,
  getSites,
  type WizardStepData,
  type WizardStepOption,
  type MatchProduct,
  type MatchArticle,
  type MatchStepInput,
  type MatchCriteria,
  type MatchResponse,
} from '@forlabs/core'
